// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAPIServerPort() {
  return window['go']['wails']['Bindings']['GetAPIServerPort']();
}

export function GetAPIToken() {
  return window['go']['wails']['Bindings']['GetAPIToken']();
}

export function GetDefaultNodeDir() {
  return window['go']['wails']['Bindings']['GetDefaultNodeDir']();
}

export function OpenDirectorySelector(arg1) {
  return window['go']['wails']['Bindings']['OpenDirectorySelector'](arg1);
}

export function OpenFileSelector(arg1) {
  return window['go']['wails']['Bindings']['OpenFileSelector'](arg1);
}
