// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function GetAPIToken():Promise<string>;

export function GetDefaultNodeDir():Promise<string>;

export function OpenDirectorySelector(arg1:frontend.OpenDialogOptions):Promise<string>;

export function OpenFileSelector(arg1:frontend.OpenDialogOptions):Promise<string>;
